server:
  port: ${PORT:8081}
  address: 0.0.0.0

spring:
  application:
    name: iam-service

app:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
